Fix many background color and table pos.
pepa-linha/Adminer-Design-Dark pull request #5
Opened 2019-10-20 10:56 UTC by shiipou

2019-10-20 13:13 UTC, shiipou commented
@pepa-linha 
I've made some change of the design to make it prettier on Chrome.
Check if it's ok for you

2019-10-27 22:12 UTC, pepa-linha requested changes
Hi, thank you for your PR. I made some changes.

2019-10-27 22:12 UTC, pepa-linha commented on adminer.css
> +    position: relative;
Relative position is not possible here - when list contains many items - that is reason why `bottom: 0` and absolute position is here

2019-10-27 22:12 UTC, pepa-linha commented on adminer.css
> +#help{
When this element is showed, please? :)

2019-10-27 22:12 UTC, pepa-linha commented on adminer.css
> +    background: #2e2c3e url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAGCAYAAADdXo4uAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBi
I do not like this change, sorry :-) Selects look like a text box with transparency color.

2019-10-27 22:12 UTC, pepa-linha commented on adminer.css
> +
Thanks

2019-10-27 22:12 UTC, pepa-linha commented on adminer.css
> +}
View link is not button here.

2019-10-27 22:12 UTC, pepa-linha commented on README.md
> +![Preview](/preview.png "Preview")
Thanks!

2019-11-07 10:34 UTC, shiipou commented
Ok, merge refused

Thanks for this great theme :)
Really love It

2019-11-07 10:34 UTC, closed without merging